### ISSUE TITLE
get_request_logger() produces error

### ISSUE THREAD

**Issue by ahmedlafta** [thangbn/json-logging-python#36]
After attempting to use the feature introduced here -> https://github.com/thangbn/json-logging-python/releases/tag/1.0.2
The project produces an error even after calling `init_request_instrument`
```
    app = Flask(__name__)
    json_logging.ENABLE_JSON_LOGGING = True
    json_logging.init_flask()
    json_logging.init_request_instrument(app)

    logger = logging.getLogger("test-logger")
    logger.setLevel(logging.DEBUG)
    logger.addHandler(logging.StreamHandler(sys.stdout))
    logger.addHandler(logging.handlers.RotatingFileHandler(
        filename="./output.log",
        maxBytes=5000000,
        backupCount=10
    ))
    request_logger = json_logging.get_request_logger()
    request_logger.addHandler(logging.handlers.RotatingFileHandler(
        filename="./output.log",
        maxBytes=5000000,
        backupCount=10
    ))


```
produces
```
RuntimeError: please init request instrument first, call init_request_instrument(app) first
```

My end goal is to redirect the http request logs to a log file as well.

After inspecting the library (internal) code, I am not seeing where `_request_logger` is ever assigned a value
https://github.com/thangbn/json-logging-python/blob/4cfe5f4785fa1650c6640bc77d3f8cf3927e4550/json_logging/__init__.py#L173

**Comment by thangbn** [comment]
will take a look

**Comment by thangbn** [comment]
i release a new version, can u verify that it is fixed

**Comment by ahmedlafta** [comment]
This fixes the error, thanks for the quick fix and new release!

Although, I'm still having an issue redirecting the flask-request-logger output to a file. Whenever I add a handler, the log statement in the file looks like thise:

```
{"type": "log", "written_at": "2019-10-03T14:04:28.588Z", "written_ts": 1570111468588188000, "component_id": "-", "component_name": "my-app", "component_instance": 0, "logger": "flask-request-logger", "thread": "Thread-17", "level": "INFO", "module": "__init__", "line_no": 57, "correlation_id": "b6eee350-e5e6-11e9-8f44-8c8590adc49e", "msg": ""}
```

Most notable the type is no longer `request` and the msg is empty.

When leaving the output to the console, the log statements look correct. Any thoughts?

**Comment by ahmedlafta** [comment]
Actually it appears to be a timing issue when adding the handler. I've updated my code to the following and it now works:

```
        req_logger = json_logging.get_request_logger()
        req_logger.handlers = []
        req_logger_handler = logging.handlers.RotatingFileHandler(
            filename=log_file_path,
            maxBytes=5000000,
            backupCount=10
        )
        req_logger_handler.setFormatter(json_logging.JSONRequestLogFormatter())
        req_logger.addHandler(req_logger_handler)
```

Basically if you add a handler to the request logger, you need to set the formatter to `JSONRequestLogFormatter`
